# Warning: Dont edit here, This file was generated automatically, using a developer tool.
def get_subparserkwg_lst():
    NoneType = type(None)
    def str_or_none(x): return None if x.lower() == "none" else x
    def intcaster(x): return int(float(x))
    
    subparserkwg_lst =     [{'cmdname': 'config',
      'clsname': 'Config',
      'hiddencli': False,
      'description': 'Interactively set configuration for prstools (run this first if you are new to prstools).\n'
                     'This command always runs interactively and prompts the user to configure\n'
                     'the prstools data directory and related settings.\n',
      'help': 'Interactively set configuration for prstools (run this first if you are new to prstools).',
      'epilog': None,
      'display_info': False,
      'modulename': 'prstools.utils',
      'groups': {'general': {'grpheader': 'Options',
                             'pkwargs': {'basics': {'args': ['-h', '--help'], 'kwargs': {'action': 'help', 'help': 'Show this help message and exit.'}},
                                         'setup': {'args': ['--setup'],
                                                   'kwargs': {'help': 'Run the interactive setup. Currently the config is -> auto_download: {auto_download}, prstdatadir: {prstdatadir}',
                                                              'type': bool,
                                                              'default': False}},
                                         'noprompt': {'args': ['--noprompt'], 'kwargs': {'help': None, 'type': bool, 'default': False}},
                                         'yes2all': {'args': ['--yes2all'], 'kwargs': {'help': 'Run setup and say yes to all the questions being asked', 'type': bool, 'default': False}},
                                         'prstdatadir': {'args': ['--prstdatadir'], 'kwargs': {'help': None, 'type': str, 'default': 'make in current directory'}},
                                         'auto_download': {'args': ['--auto_download'], 'kwargs': {'help': None, 'type': bool, 'default': True}}}}},
      'subtype': 'PRSTCLI'},
     {'cmdname': 'downloadutil',
      'clsname': 'DownloadUtil',
      'hiddencli': False,
      'description': 'Download and unpack LD reference panels and other data.\n'
                     'The files that can be downloaded and unpacked with this command includes the standard reference files for PRS-CS and PRS-CSx.\n'
                     'Additional information can be found at https://github.com/getian107/PRScsx\n',
      'help': 'Download and unpack LD reference panels and other data.',
      'epilog': None,
      'display_info': False,
      'modulename': 'prstools.utils',
      'groups': {'general': {'grpheader': 'Options',
                             'pkwargs': {'basics': {'args': ['-h', '--help'], 'kwargs': {'action': 'help', 'help': 'Show this help message and exit.'}},
                                         'destdir': {'args': ['--destdir'],
                                                     'kwargs': {'help': 'Directory in which all the data will be downloaded. Option required if you want the download to start. If you specify '
                                                                        "'prstdatadir' it will try to save to the prstdatadir (if configured).",
                                                                'type': str,
                                                                'default': 'SUPPRESS'}},
                                         'pattern': {'args': ['--pattern'],
                                                     'kwargs': {'help': 'A string pattern that retrieves every file that it matches. Matches everything by default. Without --destdir option (required to '
                                                                        'start downloading) one can see which files get matched.',
                                                                'type': str,
                                                                'default': 'ALL'}},
                                         'list': {'args': ['--list'], 'kwargs': {'help': 'Show which files can optionally be downloaded and exit.', 'type': bool, 'default': False}},
                                         'listfull': {'args': ['--listfull'], 'kwargs': {'help': 'Show complete filelist with long urls and exit.', 'type': bool, 'default': False}},
                                         'mkdir': {'args': ['--mkdir'], 'kwargs': {'help': None, 'type': bool, 'default': False}},
                                         'command': {'args': ['--command'], 'kwargs': {'help': None, 'type': NoneType, 'default': None}},
                                         'func': {'args': ['--func'], 'kwargs': {'help': None, 'type': NoneType, 'default': None}},
                                         'keeptar': {'args': ['--keeptar'],
                                                     'kwargs': {'help': 'Keep the tar.gz files in the destdir. If this option is not given they will be deleted automatically to save space.',
                                                                'type': bool,
                                                                'default': False}}}}},
      'subtype': 'PRSTCLI'},
     {'cmdname': 'transform',
      'clsname': 'Transform',
      'hiddencli': False,
      'description': 'Transform messy sumstats and other inputs into neat standardized formats\nIt can process whole directories at a time, using stars (--sst sst-prefix_*.tsv)\n',
      'help': 'Transform messy sumstats and other inputs into neat standardized formats',
      'epilog': None,
      'display_info': False,
      'modulename': 'prstools.utils',
      'groups': {'general': {'grpheader': 'Options',
                             'pkwargs': {'basics': {'args': ['-h', '--help'], 'kwargs': {'action': 'help', 'help': 'Show this help message and exit.'}},
                                         'sst': {'args': ['--sst'],
                                                 'kwargs': {'help': 'Input sumstats. Can be specified with * operator. For example "--sst CoolCohort_trait=*_hapmap3.tsv"',
                                                            'type': str,
                                                            'default': 'SUPPRESS',
                                                            'nargs': '+',
                                                            'required': True}},
                                         'colmap': {'args': ['--colmap'],
                                                    'kwargs': {'help': 'something here try default_colmap here too: {default_colmap}', 'type': str, 'default': '{default_colmap}'}},
                                         'n_gwas': {'args': ['--n_gwas'],
                                                    'kwargs': {'help': 'Manually specify gwas sample size of the input sumstats. Most often it can be extracted from the sumstat itself so you do not need '
                                                                       'to specify this.',
                                                               'type': float,
                                                               'default': None}},
                                         'out': {'args': ['--out'],
                                                 'kwargs': {'help': 'Output file name. A good suggestion: "--out {trimsst}.prstsst.tsv"', 'type': str, 'default': 'SUPPRESS', 'required': True}},
                                         'mode': {'args': ['--mode'],
                                                  'kwargs': {'help': "yooo Different modes for file handling. If 'strict' is present an error in forinstance the loading of a sumstat will lead to a stop. "
                                                                     "'redo' will force redo if output exists (else it will skip). with --mode strictredo you will combine options.",
                                                             'type': str,
                                                             'default': 'strict'}},
                                         'sep': {'args': ['--sep'], 'kwargs': {'help': 'Seperator for the inputs files, default is \\t (tab).', 'type': str, 'default': '\t'}},
                                         'n_eff_handling': {'args': ['--n_eff_handling'], 'kwargs': {'help': None, 'type': str, 'default': 'raw'}},
                                         'pyarrow': {'args': ['--pyarrow'], 'kwargs': {'help': None, 'type': bool, 'default': True}},
                                         'verbose': {'args': ['--verbose'], 'kwargs': {'help': None, 'type': bool, 'default': True}}}}},
      'subtype': 'PRSTCLI'},
     {'cmdname': 'combine',
      'clsname': 'Combine',
      'hiddencli': False,
      'description': "A tool to combine genetics-related text files. If all is well you won't need this.\n",
      'help': "A tool to combine genetics-related text files. If all is well you won't need this.",
      'epilog': None,
      'display_info': False,
      'modulename': 'prstools.utils',
      'groups': {'general': {'grpheader': 'Options',
                             'pkwargs': {'basics': {'args': ['-h', '--help'], 'kwargs': {'action': 'help', 'help': 'Show this help message and exit.'}},
                                         'input': {'args': ['--input'],
                                                   'kwargs': {'help': 'Input files to be read and combined. Inputs assumed to be delimited text files,, for now.',
                                                              'type': str,
                                                              'default': 'SUPPRESS',
                                                              'nargs': '+',
                                                              'required': True}},
                                         'out': {'args': ['--out'], 'kwargs': {'help': 'Output file name.', 'type': str, 'default': 'SUPPRESS', 'required': True}},
                                         'reqlen': {'args': ['--reqlen'],
                                                    'kwargs': {'help': 'require the number of input files to be a specific number, else procedures stops. (e.g. 22 so it combine 22 chroms)',
                                                               'type': int,
                                                               'default': 'SUPPRESS'}},
                                         'sep': {'args': ['--sep'], 'kwargs': {'help': 'Seperator for the inputs files, default is \\t (tab).', 'type': str, 'default': '\t'}},
                                         'antiglobs': {'args': ['--antiglobs'],
                                                       'kwargs': {'help': "Globs/patterns that should be removed from the input files. e.g. ['*.log'] removes files ending with .log",
                                                                  'type': list,
                                                                  'default': ['*.log', '*.tmp'],
                                                                  'nargs': '+'}},
                                         'intype': {'args': ['--intype'],
                                                    'kwargs': {'help': "Type of input file. The 'auto' default option detects this automatically based on extensions. If extension is not recognized it "
                                                                       "assumes 'headed-txt'. Other options are: 'headless-txt', 'legacyweights.tsv', 'prstweights.tsv'",
                                                               'type': str,
                                                               'default': 'auto'}},
                                         'assertunique': {'args': ['--assertunique'],
                                                          'kwargs': {'help': 'Check if the row is unique for these columns. Ignored if columns are not present. Empty list (=[]) is you want this check to '
                                                                             'not happen.',
                                                                     'type': str,
                                                                     'default': ['SNP,A1,A2'],
                                                                     'nargs': '+'}},
                                         'sortcols': {'args': ['--sortcols'],
                                                      'kwargs': {'help': 'The columns that should be used for sorting.', 'type': str, 'default': 'SUPPRESS', 'nargs': '+'}},
                                         'selectcols': {'args': ['--selectcols'],
                                                        'kwargs': {'help': 'In case not specified the columns of the input files are used.', 'type': str, 'default': 'SUPPRESS', 'nargs': '+'}},
                                         'noheader': {'args': ['--noheader'],
                                                      'kwargs': {'help': 'Dont use a header for the output file. For plink and other tools this is sometimes needed.',
                                                                 'type': bool,
                                                                 'default': None}},
                                         'outtype': {'args': ['--outtype'],
                                                     'kwargs': {'help': 'Specify the filetype to save. For now the option is tab separated file (tsv).', 'type': str, 'default': 'tsv'}},
                                         'pyarrow': {'args': ['--pyarrow'], 'kwargs': {'help': None, 'type': bool, 'default': True}},
                                         'verbose': {'args': ['--verbose'], 'kwargs': {'help': None, 'type': bool, 'default': True}}}}},
      'subtype': 'PRSTCLI'},
     {'cmdname': 'prscs2',
      'clsname': 'PRSCS2',
      'hiddencli': False,
      'description': 'PRS-CS v2: A polygenic prediction method that infers posterior SNP effect sizes under continuous shrinkage (CS) priors.',
      'display_info': True,
      'help': 'PRS-CS v2: A polygenic prediction method that infers posterior SNP effect sizes under continuous shrinkage (CS) priors.',
      'epilog': '\x1b[32m# Examples (get data, run model) --> can be directly copy-pasted (:\x1b[0m\n'
                'prst downloadutil --pattern example --destdir ./; cd example        \n'
                'prstools prscs2 --ref ldref_1kg_pop -t target --sst sumstats.tsv --n_gwas 2565 --out ./result-prscs2\n',
      'modulename': 'prstools.models._base',
      'groups': {'general': {'grpheader': 'General Options',
                             'pkwargs': {'basics': {'args': ['-h', '--help'], 'kwargs': {'action': 'help', 'help': 'Show this help message and exit.'}},
                                         'cpus': {'args': ['--cpus', '-c'],
                                                  'kwargs': {'metavar': '<num-of-cpus>',
                                                             'default': 1,
                                                             'type': int,
                                                             'help': 'The number of CPUs to use (1–5 is generally most efficient). It is generally best to first maxout (=22) --n_jobs before increasing '
                                                                     'the number of CPUs above 1. To disable set to -1.'}}}},
                 'data': {'grpheader': 'Data Arguments (only first few required)',
                          'pkwargs': {'ref': {'args': ['--ref', '-r'],
                                              'kwargs': {'required': True,
                                                         'metavar': '<dir/refcode>',
                                                         'help': "Path to the directory that contains the LD reference panel. You can download this reference data manually too with '{basecmd} "
                                                                 "downloadutil'. Current config relevant to this functionality (prstdatadir: {prstdatadir}, auto_download: {auto_download})."}},
                                      'target': {'args': ['--target', '-t'],
                                                 'kwargs': {'required': True,
                                                            'type': str_or_none,
                                                            'metavar': '<bim-prefix>',
                                                            'help': 'Specify the bim file or its prefix of desired target dataset. The bim file should be in plink format. You can also set the target to '
                                                                    "'none' in which case the variant set will not be filtered for variants present in the target set. For the --target there is also the "
                                                                    '--rsidmode option in case your bim does not contain (enough) rsids.'}},
                                      'sst': {'args': ['--sst', '-s'],
                                              'kwargs': {'required': True,
                                                         'metavar': '<file>',
                                                         'help': 'The summary statistics file from which the model will be created. The file should contain columns: SNP, A1, A2, BETA or OR, P or SE '
                                                                 'information. At the moment, the file is assumed to be tab-seperated, if you like other formats please let devs know. Alternative column '
                                                                 "names can be specified with --colmap (more info below). SNP column should contain rsid's, but if you dont have these they can now also "
                                                                 'be filled in with genomic position information, by ommitting SNP in --colmap. See \x1b[34mhttps://tinyurl.com/sstxampl\x1b[0m for a '
                                                                 'sumstat example.'}},
                                      'out': {'args': ['--out', '-o'],
                                              'kwargs': {'required': True,
                                                         'metavar': '<dir+prefix>',
                                                         'help': 'Output prefix for the results (variant weights). This should be a combination of the desired output dir + file prefix.'}},
                                      'mkdir': {'args': ['--mkdir', '-m'], 'kwargs': {'help': None, 'type': bool, 'default': False}},
                                      'n_gwas': {'args': ['--n_gwas', '-n'],
                                                 'kwargs': {'required': False,
                                                            'type': intcaster,
                                                            'metavar': '<num>',
                                                            'default': None,
                                                            'help': "Sample size of the GWAS. Not required if sumstat has a 'N' column and overrules column data if specified."}},
                                      'chrom': {'args': ['--chrom'],
                                                'kwargs': {'required': False,
                                                           'type': str,
                                                           'metavar': '<chroms>',
                                                           'default': 'all',
                                                           'help': 'Optional: Select specific chromosome to work with. You can specify a specific chromosome as e.g. "--chrom 3". All chromosomes are used '
                                                                   'by default.'}},
                                      'colmap': {'args': ['--colmap'],
                                                 'kwargs': {'type': str,
                                                            'metavar': '<colnames>',
                                                            'default': '{default_colmap}',
                                                            'help': 'Optional: Specify alterative column names for the internally used columns snp,A1,A2,beta,or,pval,se_beta,n_eff,af_A1,chrom,pos (in '
                                                                    'that order). Forinstance "--colmap rsid,a1,a2,beta_gwas,,pvalue,beta_standard_error,,,chr,bp" (OR, N, FRQA1, are excluded in this '
                                                                    'example). When the command is run a quick this_column -> that_column conversion table will be shown. Additionaly prstools has many '
                                                                    'internal checks to make sure a good PRS will be generated! The original default colmap works with the PRS-CS standard sumstat '
                                                                    'formatting.'}},
                                      'rsidmode': {'args': ['--rsidmode'],
                                                   'kwargs': {'type': str,
                                                              'metavar': '<yes/no>',
                                                              'default': 'auto',
                                                              'help': 'Optional: Add rsids to the .bim file snp column for the target after loading. This is done using chrom and position information. '
                                                                      'This can make sense if you bim file contains few rsids. By adding rsids after loading, the target can be merged with the LD '
                                                                      'reference or PRS weights.'}},
                                      'pred': {'args': ['--pred', '-p'],
                                               'kwargs': {'required': False,
                                                          'metavar': '<yes/no>',
                                                          'type': str,
                                                          'default': 'auto',
                                                          'choices': ['yes', 'no', 'auto', 'eval'],
                                                          'help': "Optional: Add this argument to set behavior for PRS generation for the induviduals in the target dataset. With the 'auto' option (which "
                                                                  "is the default) the tool tries to generate a prediction and evaluation, unless the --chrom option is set. With option 'eval' it tries "
                                                                  'to evaluate performance and throws an error if it fails. Available options: (yes/no/auto/eval).'}}}},
                 'model': {'grpheader': 'Model Arguments (all optional)',
                           'pkwargs': {'n_iter': {'args': ['--n_iter'], 'kwargs': {'help': 'Total number of MCMC iterations.', 'type': int, 'default': 1000}},
                                       'n_burnin': {'args': ['--n_burnin'],
                                                    'kwargs': {'help': 'Number of burn-in iterations if larger than 1 or fraction of n_iter if smaller than 1.', 'type': float, 'default': 0.5}},
                                       'n_slice': {'args': ['--n_slice'], 'kwargs': {'help': 'Thinning of the Markov chain.', 'type': int, 'default': 1}},
                                       'shuffle': {'args': ['--shuffle'], 'kwargs': {'help': None, 'type': bool, 'default': False}},
                                       'seed': {'args': ['--seed'], 'kwargs': {'help': 'Random seed for reproducibility.', 'type': int, 'default': -1}},
                                       'a': {'args': ['--a'], 'kwargs': {'help': 'Parameter a in the gamma-gamma prior.', 'type': float, 'default': 1.0}},
                                       'b': {'args': ['--b'], 'kwargs': {'help': 'Parameter b in the gamma-gamma prior.', 'type': float, 'default': 0.5}},
                                       'phi': {'args': ['--phi'],
                                               'kwargs': {'help': 'Global shrinkage parameter phi. If phi is not specified, it will be learnt from the data using a Bayesian approach.',
                                                          'type': float,
                                                          'default': -1.0}},
                                       'clip': {'args': ['--clip'], 'kwargs': {'help': 'Clip parameter. The default works best in pretty much all cases.', 'type': float, 'default': 1.0}},
                                       'sampler': {'args': ['--sampler'],
                                                   'kwargs': {'help': 'Sampler algorithm. The default is Rue sampling, which is the original sampler and gives good results.',
                                                              'type': str,
                                                              'default': 'default'}},
                                       'groupby': {'args': ['--groupby'], 'kwargs': {'help': None, 'type': str, 'default': 'chrom'}},
                                       'local_rm': {'args': ['--local_rm'], 'kwargs': {'help': None, 'type': bool, 'default': False}},
                                       'compute_score': {'args': ['--compute_score'], 'kwargs': {'help': None, 'type': bool, 'default': False}},
                                       'clear_linkdata': {'args': ['--clear_linkdata'], 'kwargs': {'help': None, 'type': bool, 'default': True}},
                                       'scaling': {'args': ['--scaling'], 'kwargs': {'help': None, 'type': str, 'default': 'ref'}},
                                       'pop': {'args': ['--pop'], 'kwargs': {'help': None, 'type': str, 'default': 'pop'}},
                                       'n_jobs': {'args': ['--n_jobs'], 'kwargs': {'help': 'This sets the number of jobs for parallel processing.', 'type': int, 'default': 8}},
                                       'pbar': {'args': ['--pbar'], 'kwargs': {'help': None, 'type': bool, 'default': True}},
                                       'verbose': {'args': ['--verbose'], 'kwargs': {'help': None, 'type': bool, 'default': False}}}}},
      'subtype': 'PRSTCLI'},
     {'cmdname': 'prscsx2',
      'clsname': 'PRSCSX2',
      'hiddencli': False,
      'description': 'PRS-CSx v2: Alpha implementation, A multi-ancestry polygenic prediction method     that jointly infers SNP effect sizes using coupled continuous shrinkage (CS) priors.',
      'display_info': True,
      'help': 'PRS-CSx v2: Alpha implementation, A multi-ancestry polygenic prediction method     that jointly infers SNP effect sizes using coupled continuous shrinkage (CS) priors.',
      'epilog': None,
      'modulename': 'prstools.models._base',
      'groups': {'general': {'grpheader': 'General Options',
                             'pkwargs': {'basics': {'args': ['-h', '--help'], 'kwargs': {'action': 'help', 'help': 'Show this help message and exit.'}},
                                         'cpus': {'args': ['--cpus', '-c'],
                                                  'kwargs': {'metavar': '<num-of-cpus>',
                                                             'default': 1,
                                                             'type': int,
                                                             'help': 'The number of CPUs to use (1–5 is generally most efficient). It is generally best to first maxout (=22) --n_jobs before increasing '
                                                                     'the number of CPUs above 1. To disable set to -1.'}}}},
                 'data': {'grpheader': 'Data Arguments (only first few required)',
                          'pkwargs': {'ref': {'args': ['--ref', '-r'],
                                              'kwargs': {'required': True,
                                                         'metavar': '<dir/refcode>',
                                                         'help': "Path to the directory that contains the LD reference panel. You can download this reference data manually too with '{basecmd} "
                                                                 "downloadutil'. Current config relevant to this functionality (prstdatadir: {prstdatadir}, auto_download: {auto_download})."}},
                                      'target': {'args': ['--target', '-t'],
                                                 'kwargs': {'required': True,
                                                            'type': str_or_none,
                                                            'metavar': '<bim-prefix>',
                                                            'help': 'Specify the bim file or its prefix of desired target dataset. The bim file should be in plink format. You can also set the target to '
                                                                    "'none' in which case the variant set will not be filtered for variants present in the target set. For the --target there is also the "
                                                                    '--rsidmode option in case your bim does not contain (enough) rsids.'}},
                                      'sst': {'args': ['--sst', '-s'],
                                              'kwargs': {'required': True,
                                                         'metavar': '<file>',
                                                         'help': 'The summary statistics file from which the model will be created. The file should contain columns: SNP, A1, A2, BETA or OR, P or SE '
                                                                 'information. At the moment, the file is assumed to be tab-seperated, if you like other formats please let devs know. Alternative column '
                                                                 "names can be specified with --colmap (more info below). SNP column should contain rsid's, but if you dont have these they can now also "
                                                                 'be filled in with genomic position information, by ommitting SNP in --colmap. See \x1b[34mhttps://tinyurl.com/sstxampl\x1b[0m for a '
                                                                 'sumstat example.',
                                                         'nargs': '+'}},
                                      'pop': {'args': ['--pop'],
                                              'kwargs': {'required': True,
                                                         'nargs': '+',
                                                         'type': str,
                                                         'metavar': '<pop>',
                                                         'help': 'Population(s) corresponding to the GWAS summary statistics and LD references, in the same order as --sst, --ref and --n_gwas. For '
                                                                 'example: --pop EUR AFR. Standard PRS-CSx reference populations are AFR, AMR, EAS, EUR and SAS.'}},
                                      'out': {'args': ['--out', '-o'],
                                              'kwargs': {'required': True,
                                                         'metavar': '<dir+prefix>',
                                                         'help': 'Output prefix for the results (variant weights). This should be a combination of the desired output dir + file prefix.'}},
                                      'mkdir': {'args': ['--mkdir', '-m'], 'kwargs': {'help': None, 'type': bool, 'default': False}},
                                      'n_gwas': {'args': ['--n_gwas', '-n'],
                                                 'kwargs': {'required': False,
                                                            'type': intcaster,
                                                            'metavar': '<num>',
                                                            'default': None,
                                                            'help': "Sample size of the GWAS. Not required if sumstat has a 'N' column and overrules column data if specified.",
                                                            'nargs': '+'}},
                                      'chrom': {'args': ['--chrom'],
                                                'kwargs': {'required': False,
                                                           'type': str,
                                                           'metavar': '<chroms>',
                                                           'default': 'all',
                                                           'help': 'Optional: Select specific chromosome to work with. You can specify a specific chromosome as e.g. "--chrom 3". All chromosomes are used '
                                                                   'by default.'}},
                                      'colmap': {'args': ['--colmap'],
                                                 'kwargs': {'type': str,
                                                            'metavar': '<colnames>',
                                                            'default': '{default_colmap}',
                                                            'help': 'Optional: Specify alterative column names for the internally used columns snp,A1,A2,beta,or,pval,se_beta,n_eff,af_A1,chrom,pos (in '
                                                                    'that order). Forinstance "--colmap rsid,a1,a2,beta_gwas,,pvalue,beta_standard_error,,,chr,bp" (OR, N, FRQA1, are excluded in this '
                                                                    'example). When the command is run a quick this_column -> that_column conversion table will be shown. Additionaly prstools has many '
                                                                    'internal checks to make sure a good PRS will be generated! The original default colmap works with the PRS-CS standard sumstat '
                                                                    'formatting.'}},
                                      'rsidmode': {'args': ['--rsidmode'],
                                                   'kwargs': {'type': str,
                                                              'metavar': '<yes/no>',
                                                              'default': 'auto',
                                                              'help': 'Optional: Add rsids to the .bim file snp column for the target after loading. This is done using chrom and position information. '
                                                                      'This can make sense if you bim file contains few rsids. By adding rsids after loading, the target can be merged with the LD '
                                                                      'reference or PRS weights.'}},
                                      'pred': {'args': ['--pred', '-p'],
                                               'kwargs': {'required': False,
                                                          'metavar': '<yes/no>',
                                                          'type': str,
                                                          'default': 'auto',
                                                          'choices': ['yes', 'no', 'auto', 'eval'],
                                                          'help': "Optional: Add this argument to set behavior for PRS generation for the induviduals in the target dataset. With the 'auto' option (which "
                                                                  "is the default) the tool tries to generate a prediction and evaluation, unless the --chrom option is set. With option 'eval' it tries "
                                                                  'to evaluate performance and throws an error if it fails. Available options: (yes/no/auto/eval).'}}}},
                 'model': {'grpheader': 'Model Arguments (all optional)',
                           'pkwargs': {'n_iter': {'args': ['--n_iter'], 'kwargs': {'help': 'Total number of MCMC iterations.', 'type': int, 'default': 10000}},
                                       'n_burnin': {'args': ['--n_burnin'],
                                                    'kwargs': {'help': 'Number of burn-in iterations if larger than 1 or fraction of n_iter if smaller than 1.', 'type': float, 'default': 0.5}},
                                       'n_slice': {'args': ['--n_slice'], 'kwargs': {'help': 'Thinning of the Markov chain.', 'type': int, 'default': 1}},
                                       'shuffle': {'args': ['--shuffle'], 'kwargs': {'help': None, 'type': bool, 'default': False}},
                                       'seed': {'args': ['--seed'], 'kwargs': {'help': 'Random seed for reproducibility.', 'type': int, 'default': -1}},
                                       'a': {'args': ['--a'], 'kwargs': {'help': 'Parameter a in the gamma-gamma prior.', 'type': float, 'default': 1.0}},
                                       'b': {'args': ['--b'], 'kwargs': {'help': 'Parameter b in the gamma-gamma prior.', 'type': float, 'default': 0.5}},
                                       'phi': {'args': ['--phi'],
                                               'kwargs': {'help': 'Global shrinkage parameter phi. If phi is not specified, it will be learnt from the data using a Bayesian approach.',
                                                          'type': float,
                                                          'default': -1.0}},
                                       'clip': {'args': ['--clip'], 'kwargs': {'help': 'Clip parameter. The default works best in pretty much all cases.', 'type': float, 'default': 1.0}},
                                       'sampler': {'args': ['--sampler'],
                                                   'kwargs': {'help': 'Sampler algorithm. The default is Rue sampling, which is the original sampler and gives good results.',
                                                              'type': str,
                                                              'default': 'default'}},
                                       'groupby': {'args': ['--groupby'], 'kwargs': {'help': None, 'type': str, 'default': 'chrom'}},
                                       'local_rm': {'args': ['--local_rm'], 'kwargs': {'help': None, 'type': bool, 'default': False}},
                                       'compute_score': {'args': ['--compute_score'], 'kwargs': {'help': None, 'type': bool, 'default': False}},
                                       'clear_linkdata': {'args': ['--clear_linkdata'], 'kwargs': {'help': None, 'type': bool, 'default': True}},
                                       'scaling': {'args': ['--scaling'], 'kwargs': {'help': None, 'type': str, 'default': 'ref'}},
                                       'n_jobs': {'args': ['--n_jobs'], 'kwargs': {'help': 'This sets the number of jobs for parallel processing.', 'type': int, 'default': 8}},
                                       'pbar': {'args': ['--pbar'], 'kwargs': {'help': None, 'type': bool, 'default': True}},
                                       'verbose': {'args': ['--verbose'], 'kwargs': {'help': None, 'type': bool, 'default': False}}}}},
      'subtype': 'PRSTCLI'},
     {'cmdname': 'multiprs',
      'clsname': 'MultiPRS',
      'hiddencli': False,
      'description': 'MultiPRS: Generates polygenic risk scores if you give it weights. \nNote: currently one needs to run "prst config" first.\n',
      'display_info': True,
      'help': 'MultiPRS: Generates polygenic risk scores if you give it weights. ',
      'epilog': None,
      'modulename': 'prstools.models._base',
      'groups': {'general': {'grpheader': 'General Options',
                             'pkwargs': {'basics': {'args': ['-h', '--help'], 'kwargs': {'action': 'help', 'help': 'Show this help message and exit.'}},
                                         'cpus': {'args': ['--cpus', '-c'],
                                                  'kwargs': {'metavar': '<num-of-cpus>',
                                                             'default': 1,
                                                             'type': int,
                                                             'help': 'The number of CPUs to use (1–5 is generally most efficient). It is generally best to first maxout (=22) --n_jobs before increasing '
                                                                     'the number of CPUs above 1. To disable set to -1.'}}}},
                 'data': {'grpheader': 'Data Arguments (only first few required)',
                          'pkwargs': {'weights': {'args': ['--weights', '-w'],
                                                  'kwargs': {'help': 'The weight file(s) for the PRS. Can be specified with * operator. For example "-w greatprsweights_trait=*.tsv".  ergerg',
                                                             'required': True,
                                                             'metavar': '<file>',
                                                             'type': str,
                                                             'nargs': '+'}},
                                      'target': {'args': ['--target', '-t'],
                                                 'kwargs': {'required': True,
                                                            'type': str_or_none,
                                                            'metavar': '<bim-prefix>',
                                                            'help': 'Specify the bim file or its prefix of desired target dataset. The bim file should be in plink format. You can also set the target to '
                                                                    "'none' in which case the variant set will not be filtered for variants present in the target set. For the --target there is also the "
                                                                    '--rsidmode option in case your bim does not contain (enough) rsids.'}},
                                      'out': {'args': ['--out', '-o'],
                                              'kwargs': {'required': True,
                                                         'metavar': '<dir+prefix>',
                                                         'help': 'Output prefix for the results (variant weights). This should be a combination of the desired output dir + file prefix.Suggestion: "--out '
                                                                 '{trimweights}_{target}".'}},
                                      'mkdir': {'args': ['--mkdir', '-m'], 'kwargs': {'help': None, 'type': bool, 'default': False}},
                                      'rsidmode': {'args': ['--rsidmode'],
                                                   'kwargs': {'type': str,
                                                              'metavar': '<yes/no>',
                                                              'default': 'auto',
                                                              'help': 'Optional: Add rsids to the .bim file snp column for the target after loading. This is done using chrom and position information. '
                                                                      'This can make sense if you bim file contains few rsids. By adding rsids after loading, the target can be merged with the LD '
                                                                      'reference or PRS weights.'}},
                                      'pred': {'args': ['--pred', '-p'],
                                               'kwargs': {'required': False,
                                                          'metavar': '<yes/no>',
                                                          'type': str,
                                                          'default': 'auto',
                                                          'choices': ['yes', 'no', 'auto', 'eval'],
                                                          'help': "Optional: Add this argument to set behavior for PRS generation for the induviduals in the target dataset. With the 'auto' option (which "
                                                                  "is the default) the tool tries to generate a prediction and evaluation, unless the --chrom option is set. With option 'eval' it tries "
                                                                  'to evaluate performance and throws an error if it fails. Available options: (yes/no/auto/eval).'}}}},
                 'model': {'grpheader': 'Model Arguments (all optional)',
                           'pkwargs': {'mode': {'args': ['--mode'],
                                                'kwargs': {'help': "Different modes for file handling. If 'strict' is present an error in forinstance the loading of a weight will lead to a stop. ",
                                                           'type': str,
                                                           'default': 'strict'}},
                                       'missing': {'args': ['--missing'], 'kwargs': {'help': None, 'type': str, 'default': 'flex'}},
                                       'val': {'args': ['--val'], 'kwargs': {'help': None, 'type': NoneType, 'default': None}},
                                       'groupby': {'args': ['--groupby'], 'kwargs': {'help': None, 'type': str, 'default': 'SUPPRESS'}},
                                       'pbar': {'args': ['--pbar'], 'kwargs': {'help': None, 'type': bool, 'default': True}},
                                       'verbose': {'args': ['--verbose'], 'kwargs': {'help': None, 'type': bool, 'default': False}}}}},
      'subtype': 'PRSTCLI'}]
    return subparserkwg_lst